services:
  - type: web
    name: echerha-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: ВСТАВ_СВІЙ_ТОКЕН_СЮДИ
